### ISSUE TITLE
dependency ‘spatstat’ is not available for package ‘alphahull’

### ISSUE THREAD

**Issue by chenxofhit** [jw156605/SLICER#2]
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpqqPzdp/devtools325a203c0c21/alphahull'  \
  --library='/home/chenx/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

ERROR: dependency ‘spatstat’ is not available for package ‘alphahull’
* removing ‘/home/chenx/R/x86_64-pc-linux-gnu-library/3.2/alphahull’
Error: Command failed (1)

How can I solve this problem?

**Comment by jw156605** [comment]
I've never encountered this error before. Did you try installing spatstat,
then reinstalling alphahull? The only other thing I can think to try is to
update your version of R.
