### ISSUE TITLE
In areaahull(alpha_hull) : Problem in area computation (Returns NA)

### ISSUE THREAD

**Issue by kaizen89** [jw156605/SLICER#3]
when executing: " k = select_k(traj[,genes], kmin=5) "on the sample data, I get this message:
In areaahull(alpha_hull) : Problem in area computation (Returns NA)

**Comment by jw156605** [comment]
I'm guessing that this is an R version issue. Please try upgrading R to the latest version and re-installing SLICER (along with required libraries) to upgrade these packages to their latest versions.
