### ISSUE TITLE
Plotting Actual Stages to infer trajectory movement

### ISSUE THREAD

**Issue by csbbcompbio** [jw156605/SLICER#6]
Dear Authors,
Hope you are doing fine. Here i am attaching the figure 4 from your paper on SLICER. In this figure for part A you were able to incorporate the stage/sample assignments which really helps you to understand the trajectory biologically. In my case Slicer using numbers to denote the points which basically is of no use until you see the assignments on the plot. cells_ordered helps in way but visual can really help me explain lot of things. If you can help me with the command that you used to incorporate the actual sample names then that would be really helpful.

PS : I have my data in three stages combined in a matrix [That is cells from three different stages]
Thanks,

Cheers !!

Praneet

**Comment by csbbcompbio** [comment]
![fig4_slicer](https://user-images.githubusercontent.com/20099278/29984286-b27ea80e-8f27-11e7-827f-2d22b796989a.gif)
Attached is the figure

**Comment by jw156605** [comment]
Just set up a vector of symbols, with different symbols corresponding to different time points. Then you can pass symbols into the trajectory plotting function.

**Comment by csbbcompbio** [comment]
Is it possible for you to provide a example ?
As the example will really help me understand the type of vector that is rownames in matrix and the corresponding symbol or whatever Slicer accepts and how exactly to use it in the function plotting the trajectory.
Examples can make life easy and saves the time one spent beating around the bush.

**Comment by jw156605** [comment]
cell_symbols = rep(16,num_cells)
cell_symbols[DAY0] = 15
cell_symbols[DAY2] = 17
graph_process_distance(traj_graph, embedding, start, cell_symbols)

**Comment by csbbcompbio** [comment]
Awesome. 

Thanks,

Cheers !!

Praneet

**Comment by csbbcompbio** [comment]
Hi Joshua,
Thanks a ton. I got the result. I have a matrix of 1230 cells and 14773 genes.

> cell_symbols <- c(rep("*", 429), rep("+", 423),rep("-", 400))
> graph_process_distance(traj_graph, traj_lle, start, cell_symbols)

I have attached the plot. Do recommend using any other steps after this plot ?
[Plot_Traj.pdf](https://github.com/jw156605/SLICER/files/1278936/Plot_Traj.pdf)

Thanks,

Cheers !!

Praneet

**Comment by jw156605** [comment]
Looks like a clear example of a branching trajectory! I would do branch detection and look at the expression patterns of some marker genes to see if their expression profiles make sense.

**Comment by csbbcompbio** [comment]
Thanks Joshua. I really appreciate it.


Cheers !!

Praneet

**Comment by csbbcompbio** [comment]
Hi Joshua,
Can you please add https://cran.r-project.org/web/packages/SLICER/SLICER.pdf on your github page as I have been SLICER for almost a week and have not been able to find this pdf till today.


Thanks,

Cheers !!

Praneet

**Comment by jw156605** [comment]
No, I think it's clear enough. There's a link to the CRAN repository on the Github page. You can also access the SLICER documentation from inside R just like you would with any other R package.

**Comment by csbbcompbio** [comment]
Anyways, Thanks for all your guidance. I just mentioned as I could not find the link to the pdf on the github. I found it using google search.

Thanks again,

Cheers !!

Praneet
